Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 2048
  end

  # Optional: private network (NAT is default)
  # config.vm.network "private_network", type: "dhcp"
end
