Vagrant.configure("2") do |config|

  config.vm.box = "debian/trixie64"
  config.vm.box_version = "13.20260121.1"
  config.vm.synced_folder ".", "/vagrant", disabled: true # Disable the default synced folder. This is causing problems with my host machine.

  config.vm.define "dpentlanS" do |control|
    control.vm.hostname = "dpentlanS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024 # may need to lower to 512 for school computers
      libvirt.cpus = 2 # may need to lower to 1 for school computers
    end
    control.vm.provision "file", 
      source: "confs/k3s-config.yaml",
      destination: "/home/vagrant/k3s-config.yaml"
    control.vm.provision "file", 
      source: "confs/traefik-values.yaml",
      destination: "/home/vagrant/traefik-values.yaml"
    control.vm.provision "file", 
      source: "confs/first-app-ingress.yaml",
      destination: "/home/vagrant/first-app-ingress.yaml"
    control.vm.provision "file", 
      source: "confs/first-app-service.yaml",
      destination: "/home/vagrant/first-app-service.yaml"
    control.vm.provision "shell", inline: <<-SHELL
      set -eux
      # move k3s config file and give correct permissions
      sudo mkdir -p /etc/rancher/k3s
      sudo mv /home/vagrant/k3s-config.yaml /etc/rancher/k3s/config.yaml
      sudo chown root:root /etc/rancher/k3s/config.yaml
      sudo chmod 644 /etc/rancher/k3s/config.yaml
    SHELL
    control.vm.provision "shell", path: "scripts/bootstrap.sh"
  end
end
