Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2310"
  config.vm.box_version = "4.3.12"

  config.vm.define "dpentlanS" do |control|
    control.vm.hostname = "dpentlanS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024 # may need to lower to 512 for school computers
      libvirt.cpus = 2 # may need to lower to 1 for school computers
    end
    control.vm.provision "file", 
      source: "confs/k3s-config-server.yaml",
      destination: "/home/vagrant/k3s-config.yaml"
    control.vm.provision "shell", inline: <<-SHELL
      set -eux
      sudo mkdir -p /etc/rancher/k3s
      sudo mv /home/vagrant/k3s-config.yaml /etc/rancher/k3s/config.yaml
      sudo chown root:root /etc/rancher/k3s/config.yaml
      sudo chmod 644 /etc/rancher/k3s/config.yaml
    SHELL
    control.vm.provision "shell", path: "scripts/bootstrap_server.sh"
  end

  config.vm.define "dpentlanSW" do |control|
    control.vm.hostname = "dpentlanSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024 # may need to lower to 512 for school computers
      libvirt.cpus = 2 # may need to lower to 1 for school computers
    end
    control.vm.provision "file", 
      source: "confs/k3s-config-worker.yaml",
      destination: "/home/vagrant/k3s-config.yaml"
    control.vm.provision "shell", inline: <<-SHELL
      set -eux
      sudo mkdir -p /etc/rancher/k3s
      sudo mv /home/vagrant/k3s-config.yaml /etc/rancher/k3s/config.yaml
      sudo chown root:root /etc/rancher/k3s/config.yaml
      sudo chmod 644 /etc/rancher/k3s/config.yaml
    SHELL
    control.vm.provision "shell", path: "scripts/bootstrap_worker.sh"
  end

end
