Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2310"
  config.vm.box_version = "4.3.12"

  config.vm.define "dpentlanS" do |control|
    control.vm.hostname = "dpentlanS"
    control.vm.network "private_network", ip: "192.168.56.110" # may have to change to public_network if you need to connect to apps running inside these VMs.
    # control.vm.network "public_network", ip: "192.168.56.110", :dev => enp0s3
    control.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      # libvirt.memory = 512
      # libvirt.cpus = 1
      libvirt.memory = 1024
      libvirt.cpus = 2
    end
    control.vm.provision "shell", path: "scripts/bootstrap_server.sh"
  end

  config.vm.define "dpentlanSW" do |control|
    control.vm.hostname = "dpentlanSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    # control.vm.network "public_network", ip: "192.168.56.111"
    control.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      # libvirt.memory = 512
      # libvirt.cpus = 1
      libvirt.memory = 1024
      libvirt.cpus = 2
    end
    control.vm.provision "shell", path: "scripts/bootstrap_worker.sh"
  end

end
