Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2404"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 2048
    libvirt.cpus = 2
  end
end
