#!/bin/bash

set -ux
# e: exit the script when a command returns an error. 
# u: treat unset variables as errors. 
# x: print the command to the terminal before executing.

SERVER_HOST=dpentlanS
WORKER_HOST=dpentlanSW
SERVER_IP=192.168.56.110
WORKER_IP=192.168.56.111
TOKEN_SRC="/var/lib/rancher/k3s/server/node-token"
TOKEN_DST_DIR="/home/vagrant/shared"
TOKEN_DST="${TOKEN_DST_DIR}/token"

echo "Running bootstrap_server.sh"

# sudo apt update
# sudo apt upgrade -y
sudo apt install -y curl

# Install k3s
curl -sfL https://get.k3s.io | sh -

# Create token file and dir
mkdir -p "$TOKEN_DST_DIR"
touch "$TOKEN_DST"

# Wait for token source file to be generated by k3s
until sudo test -s "$TOKEN_SRC"; do
  echo "Waiting for k3s token..."
  sleep 1
done
echo "k3s token generated."

# Wait for API server to initialize
until sudo k3s kubectl get --raw='/readyz' >/dev/null 2>&1; do
  echo "Waiting for k3s API server..."
  sleep 2
done
echo "k3s API in ready state."

# Copy token to a destination file for access via ssh.
sudo cat "$TOKEN_SRC" | tee "$TOKEN_DST" > /dev/null
sudo chmod 644 "$TOKEN_DST"

# show token to stdout for debug
cat "$TOKEN_DST"